name: CI SonarQube Integration
on:
  push:
    branches:
      - main
      - feature
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-and-analyze:
    name: Setup, Test & Scan
    runs-on: macos-latest
    steps:
      - name: Checkout # checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup # setup python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install # install required dependencies
        run: python3 -m pip3 install --upgrade pip3 && pip3 install -r requirements.txt
      - name: Test # test & generate coverage report
        run: pytest --cov=src --cov-report xml:coverage.xml
      - name: Scan # scan with sonarqube
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}